name: Build Unsigned Debug IPA

on:
  push:
    branches: [ "main", "ui-update" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Debug IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' Antrag.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' Antrag.xcodeproj/project.pbxproj
          
      - name: Archive Build (Debug, Unsigned)
        run: |
          xcodebuild clean archive \
            -workspace Antrag.xcworkspace \
            -scheme "Antrag" \
            -configuration Debug \
            -archivePath build/Antrag.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            IPHONEOS_DEPLOYMENT_TARGET=16.0
            
      - name: Create IPA from Archive
        run: |
          # Copy the .app from the archive
          cp -R build/Antrag.xcarchive/Products/Applications/Antrag.app .
          # Package the app into an IPA
          mkdir -p Payload
          cp -R Antrag.app Payload/
          zip -r Antrag.ipa Payload
          rm -rf Payload Antrag.app
          
      - name: Upload Debug IPA
        uses: actions/upload-artifact@v4
        with:
          name: Antrag-Debug.ipa
          path: Antrag.ipa
          retention-days: 90
